### ISSUE TITLE
Not predicting on PROD

### ISSUE THREAD

**Issue by robert-sanfeliu** [eu-nebulous/exponential-smoothing-predictor#17]
The predictor is not providing any prediction for the application on PROD environment
Multiple applications have been deployed on that environment. According to the logs ,predictor seems to be trying to periodically predict for app 3b05c006b3af (failing because there is no data), but won't try to predict for newer apps: 0df9af281283 and 191167a3555d

**Comment by atsag** [comment]
Please, try to replicate the issue following the most recent changes

**Comment by robert-sanfeliu** [comment]
It is fixed
